apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: springboot-app:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: GROQ_API_KEY
              value: "gsk_VOTRE_CLE_GROQ_ICI"

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-svc
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort