# PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/miola
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8080

# JWT
jwt.secret=cetteCleDoitFaireAuMoins32CaracteresLongue123456

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Spring AI
# Clé vient de docker-compose
spring.ai.openai.api-key=${GROQ_API_KEY:vide}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.completions-path=/v1/chat/completions

